services:
  - type: web
    name: euskara-ageria
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.11.9
    autoDeploy: true
